model-name: hybridUnet_crop
device: cuda
model:
  input_channel: 3
  output_classes: 1
  bilinear: true

train:
  epoch: 300
  batch-size: 16
  criterion:
    # name: dice
    name: crossentropyloss
  optimizer:
    name: adamw
    learning-rate: 0.00001
    args:
      betas: [0.9, 0.999]
  lr_scheduler:
    # name: plateau
    # args:
    #   patience: 5
    name: multisteplr
    args:
      milestones: [5,10,15,20]
      gamma: 0.5
  log-interval: 10

test:
  batch-size: 256
